### PR TITLE
Please review the issue I have identified

### PR DESCRIPTION
**Pull request by thale5**
I wrote a description in README.md.

### CODE REVIEW

**Comment by Knighth** [comment]
Yeah I actually was aware of this issue somewhat with custom trees and at the time didn't have good fix for it, but had since forgotten about it.
Your fix look\sound like a good solution, let me just review it a bit more to make sure I understand it! :)

**Comment by thale5** [comment]
Thanks for looking at it!

m_encodedArray setup looks strange because it is quite non-public. The rest is straightforward.

**Comment by Knighth** [comment]
So basically you're calling dummy serialize on 262145+ trees to increment their refcounter... as the first 262144 have that done as part of the normal real prefab-treeinfo serialize call, I get that. I get the reflection to temp replace the encodedarray with nothing for the purpose of actually writing nothing while invoking the ref counting parts of the underlying treeinfo prefab collection serialize routine for those > 262144.  I think I understand how that helps with keeping the prefab indexes from changing around (for custom trees) as one adds and removes tress from their subscriptions\enabled\disable etc.. though trying to find where that refcount is used in the deserialize process to lock\patch things was headache inducing and unsuccessful on my part.  Basically I don't get how incrementing the ref count but not really calling prefab-treeinfo serialize on the >262k tree indexes still some how saves that needed data.

However I couldn't repo your results exactly:
.... to repo 
in the step about enabling a couple more trees.. I had to add a step of disabling the original custom tree.  This of course has the side effect mentioned above of shifting the index to be another tree (which I as mentioned I was aware of couldn't come up with a way to solve).
Which I kind of thought wasn't always bad vs...getting a null-ref message but certainly I would prefer they stick if possible.

Using the new code .. with the same steps (as above)...
Now I just get null ref's and massive display glitches...instead of just the wrong trees and crashes\hangs when I try to go back to main menu. But yes, re-enabling the missing assets does put them back correctly.

Which is better for the user though? Previously I had thought well...better to have it error less and load the wrong trees then bomb, now with some of the loading screen mods where people can see what assets they're actually missing maybe just bombing out is better?

**Comment by Knighth** [comment]
edited above..

Plus... hmm maybe I can just write up something to detect the fact there are missing tree assetts and provide a config option to replace missing trees with whatever tree is in tree-prefab index 0 (a standard tree), as it would be away around the null-ref explosions for those that don't want to hunt down the asset in question or for assets that aren't available anymore etc. 

Also... I must have been 1/2 asleep earlier... I see the where the other work I was missing before is being done inside the collections 'EndSerialize' now... total brain fart last night on that... and it's been awhile since I dug into this stuff)

**Pull request merged**
